version: 0.2

phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region eu-north-1 | docker login --username AWS --password-stdin 148761647602.dkr.ecr.eu-north-1.amazonaws.com
  build:
    commands:
      - docker build -t bank-deposit-prediction .
      - docker tag bank-deposit-prediction:latest 148761647602.dkr.ecr.eu-north-1.amazonaws.com/bank-deposit-prediction:latest
  post_build:
    commands:
      - docker push 148761647602.dkr.ecr.eu-north-1.amazonaws.com/bank-deposit-prediction:latest
      - echo Writing image definitions file...
      - printf '[{"name":"bank-deposit-prediction","imageUri":"%s"}]' 505076619770.dkr.ecr.us-east-1.amazonaws.com/bank-deposit-prediction:latest > imagedefinitions.json   
artifacts:
  files: imagedefinitions.json